permissions: {}
name: Publish to DockerHub
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        name: Checkout
        with:
          fetch-depth: 0
      - uses: Amadevus/pwsh-script@97a8b211a5922816aa8a69ced41fa32f23477186
        name: 'Docker: generating quality reports (testing & linting)'
        id: compute-versions
        with:
          script: |
            $gitVersion = git describe --tags
            $latestMajorTag = ''
            $latestTag = ''
            if ($gitVersion -match '^\d.\d.\d$') {
              # get all tags in semver order oldest to newest
              $tags = git tag -l --sort=version:refname  | Where-Object { $_ -Match '^\d\.\d\.\d$' }
              # get the latest released semver
              $latestVersion = $tags[$tags.Count - 1]
              # get the latest released semver for the tag being processed
              $majorVersionMatch =  $gitVersion | Select-String -Pattern '^\d+(?=\.)'
              $majorVersion = $majorVersionMatch.Matches[0].Value
              # get latest for this major version
              $latestMajorVersion = $tags | Where-Object { $_ -Match "^$($majorVersion)(?=\.)" } | Select-Object -Last 1
              # compute latest tag
              if([version]$gitVersion -ge [version]$latestMajorVersion) {
                # it's equal to or greater than
                # add latest tag to output
                $latestMajorTag = ", tkilminster/docker-external-dns:$($majorVersion)-latest"
              }
              if([version]$gitVersion -ge [version]$latestVersion) {
                $latestTag = ', tkilminster/docker-external-dns:latest'
              }
            }
            return "tkilminster/docker-external-dns:$($gitVersion)$($latestMajorTag)$($latestTag)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
        with:
          push: true
          tags: ${{ steps.compute-versions.outputs.result }}
