name: Continous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  checks: write
  pull-requests: write
jobs:
  quality_tests:
    name: Quality Tests (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runs-on: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            runs-on: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: Amadevus/pwsh-script@97a8b211a5922816aa8a69ced41fa32f23477186
        name: "Docker: generating quality reports (testing & linting)"
        with:
          script: |
            $name = "docker-compose-external-dns.quality.${{ matrix.arch }}.$(New-Guid)"
            $platform = "${{ matrix.platform }}"

            New-Item -ItemType Directory -Force -Path "output/reports" | Out-Null

            docker build --platform $platform --target tests --tag $name .
            docker run --platform $platform -u root -v /var/run/docker.sock:/var/run/docker.sock --name $name -a stdin -a stdout -a stderr $name
            docker cp "$($name):/app/reports" "./output/reports"
            docker container rm $name
            docker image rm $name
      - uses: actions/upload-artifact@v4
        name: Upload test reports
        with:
          name: reports-${{ matrix.arch }}
          path: output/reports/
          if-no-files-found: error
  quality_gateway:
    name: Quality Gateway
    if: success()
    needs: quality_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Download amd64 reports
        with:
          name: reports-amd64
          path: output/reports/amd64
          if-no-files-found: error
      - uses: actions/download-artifact@v4
        name: Download arm64 reports
        with:
          name: reports-arm64
          path: output/reports/arm64
          if-no-files-found: error
      - uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe
        name: Publish Test Report
        with:
          report_paths: "./output/reports/*/*junit*.xml"
          fail_on_failure: true
          include_passed: true
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          api-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: "output/reports/amd64/*cobertura*.xml"
      - uses: gaelgirodon/ci-badges-action@e2b7770c45a7c4be54af8b4b046afdeb09898dc4
        name: Generate CI badges
        if: github.ref == 'refs/heads/main'
        with:
          gist-id: 26bea053b867128f6f37f5aac0ddcf8b
          token: ${{ secrets.GIST_TOKEN }}
