name: Continous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  checks: write
  pull-requests: write
jobs:
  quality_gateway:
    name: Quality Gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: Amadevus/pwsh-script@v2
        name: "Docker: generating quality reports (testing & linting)"
        id: script
        with:
          script: |
           $identity = New-Guid
            $name = "docker-compose-external-dns.quality.$identity"
            docker build --target tests --tag $name .
            docker run -v /var/run/docker.sock:/var/run/docker.sock --name $name -a stdin -a stdout -a stderr $name
            mkdir output
            docker cp "$($name):/app/src" "./output/src"
            docker cp "$($name):/app/reports" "./output/reports"
            docker container rm $name
            docker image rm $name  
      - uses: mikepenz/action-junit-report@v4
        name: Publish Test Report
        if: success() || failure()
        with:
          report_paths: './output/reports/*junit*.xml'
          fail_on_failure: true
          include_passed: true
      - uses: 5monkeys/cobertura-action@master
        name: Publish Coverage
        with:
          path: './output/reports/*cobertura*.xml'
          minimum_coverage: 75
          fail_below_threshold: true
      
      

